### ISSUE TITLE
is this the os with onered square or a cube it may have two but i cant remember

### ISSUE THREAD

**Issue by espero-dev** [austanss/skylight#12]
i want to know to take a look at the project i think it is skylight but i cant remember i was just messing around with it a bit

**Comment by espero-dev** [comment]
@austanss can you send me a picture of the os please

**Comment by austanss** [comment]
No, it's not.

**Comment by espero-dev** [comment]
Yea I think I found the one I was thinking about it’s all a blur to me rn

**Comment by espero-dev** [comment]
But if I had a USB to sata cable I could get the source code for it but I don’t have one no more mine broke
